// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1dizushyHQ6HcTdI-ETNONR1CRk4bOk',
    appId: '1:509854375437:ios:55480220dc3ac6f1c3bf44',
    messagingSenderId: '509854375437',
    projectId: 'missing-person-app-seeth-7a51a',
    storageBucket: 'missing-person-app-seeth-7a51a.firebasestorage.app',
    iosBundleId: 'com.example.missingPersonApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1dizushyHQ6HcTdI-ETNONR1CRk4bOk',
    appId: '1:509854375437:ios:55480220dc3ac6f1c3bf44',
    messagingSenderId: '509854375437',
    projectId: 'missing-person-app-seeth-7a51a',
    storageBucket: 'missing-person-app-seeth-7a51a.firebasestorage.app',
    iosBundleId: 'com.example.missingPersonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVDOrnEYULspgwzNvpljOJgpjmFfOIV_U',
    appId: '1:509854375437:web:0644eb5a319fa49bc3bf44',
    messagingSenderId: '509854375437',
    projectId: 'missing-person-app-seeth-7a51a',
    authDomain: 'missing-person-app-seeth-7a51a.firebaseapp.com',
    storageBucket: 'missing-person-app-seeth-7a51a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDOrnEYULspgwzNvpljOJgpjmFfOIV_U',
    appId: '1:509854375437:web:0644eb5a319fa49bc3bf44',
    messagingSenderId: '509854375437',
    projectId: 'missing-person-app-seeth-7a51a',
    authDomain: 'missing-person-app-seeth-7a51a.firebaseapp.com',
    storageBucket: 'missing-person-app-seeth-7a51a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA0Un2a2ogx25fjbhv4LK2Tm0NALEQFPc',
    appId: '1:509854375437:android:3d9786a5aa8487f0c3bf44',
    messagingSenderId: '509854375437',
    projectId: 'missing-person-app-seeth-7a51a',
    storageBucket: 'missing-person-app-seeth-7a51a.firebasestorage.app',
  );
}
